config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'students#index'
  resources :students
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/student.rb
class Student < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def index
    @students = Student.all
  end
  def new
    @student = Student.new
  end
  def show
    puts "======params=====#{params.inspect}====================="
    @student=Student.find(params[:id])
  end
  def create
    puts "======params=====#{params.inspect}====================="
    @student = Student.new(student_params)
    if @student.save
      redirect_to root_path
    else
      render :new
    end

  end
  def edit
    puts "======params=====#{params.inspect}====================="
    @student = Student.find(params[:id])
  end
  def update
    @student = Student.find(params[:id])
    if @student.update(student_params)
      redirect_to root_path
    else
      render :edit
    end
  end
  def destroy
    @student=Student.find(params[:id])
    @student.destroy
    redirect_to root_path
  end

  private

  def student_params
    params.require(:student).permit(:name, :roll_no)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/home/index.html.erb
<h1>Demo</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Demo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/students/edit.html.erb
<h1>Edit Student</h1>

<%=form_for @student do |form| %>

  <p><%=form.label :name %>
    <%=form.text_field :name %></p>

  <p><%=form.label :roll_no %>
    <%=form.text_field :roll_no %></p>

  <p><%=form.submit %></p>

<%end %>

<%=link_to :back, root_path %>

app/views/students/index.html.erb
<h1>Student's data</h1>

<%=link_to 'New User', new_student_path %>
<table>
  <tr>
    <th>Name</th>
    <th>Show</th>
    <th>Edit</th>
    <th>Delete</th>
  </tr>
  <%@students.each do |student| %>
   <tr>
    <td><%=student.name %></td>
     <td><%=link_to :show, student_path(student.id) %></td>
     <td><%=link_to :edit, edit_student_path(student.id) %></td>
     <td><%=link_to :Delete, student_path(student.id), data: { confirm: "Are you Sure", :method => :delete} %></td>

     <td></td>
   </tr>
  <% end %>
</table>

app/views/students/new.html.erb
<h1>New Student</h1>

<%=form_for @student do |form| %>

  <p><%=form.label :name %>
  <%=form.text_field :name %></p>

  <p><%=form.label :roll_no %>
    <%=form.text_field :roll_no %></p>

  <p><%=form.submit %></p>

<%end %>

<%=link_to :back, root_path %>

app/views/students/show.html.erb
<h1>Student data</h1>

Name <label><%= @student.name%></label>
Roll Number <label><%= @student.roll_no %></label>